### PR TITLE
adds "initial" bound attribute to pass current $scope variable contai…

### PR DESCRIPTION
**Pull request by itjustwerks**
adds "initial" bound attribute to pass current $scope variable containing date value that should be pre-selected. adds "autocomplete = off" to input template to prevent overlap of previous entries over the calendar
# 

I really like the simplicity of this date picker, and the styling you provide is a great look.

I have made a few small changes locally to allow passing an "initial" attribute that contains a $scope variable with a date (or date string) to be used as the pre-selected date value in the picker. If no "initial" attribute is provided, the picker behaves as it does currently. Is there another way to pre-define the date that I missed? My use-case is in an editable form where you may come back to it in the future to change the selected date.

Also, I added the attribute autocomplete="off" to the input element in the template to prevent any previously entered values from showing up over the calendar. I'm not sure if that's an issue in all browsers, but it was in MS Edge at least.

### CODE REVIEW

**Comment by ricardoduarte** [comment]
@itjustwerks Hi, I tried to use your implementation and it didn't work. How can I set a date in string form?

**Comment by itjustwerks** [comment]
I am passing the date as a string in the format "MM/DD/YYYY", but you should be able to pass any date-ish string or an actual JS date to it as it uses MomentJS to convert it in the directive. What are you passing in the initial attribute? Example, where vm.property.dateTagged = "8/13/2015":

```
<ng-datepicker name="dateTagged" id="dateTagged" ng-model="vm.property.dateTagged" initial="vm.property.dateTagged" placeholder="Pick a date" format="MM/DD/YYYY" view-format="MM/DD/YYYY"></ng-datepicker>
```

**Comment by itjustwerks** [comment]
@jkuri It looks like you merged the bower.json file to include the homepage linking back to my forked code. You might want to change that back to your own :-).

Also, I have another update that adds a "Today" button under the calendar and a "clear" link to remove the date from the input field. I'll add another PR later after I've tested that further. Sorry my line endings are different than yours too. Makes the diff look like the whole file changed. I'll see if I can change that setting in my editor.

**Comment by jkuri** [comment]
Thanks for notice :-)

**Comment by jkuri** [comment]
I've added the initial bound attribute, I believe the proper way to do it is via ngModel.$render. Please check out my last commit.

**Pull request merged**
